### ISSUE TITLE
App Crashes When Attempting to View Stats / AlDente Pro / MacBook Pro 15" Late 2016 

### ISSUE THREAD

**Issue by tcpulley** [davidwernhart/AlDente-Charge-Limiter#1023]
Bug:  When I open the settings dialog and click on the Stats menu bar icon the app crashes. 
Expected Behavior: The app shouldn't crash. 

I'm running AlDente Pro 1.22.2 (42) on a late 2016 15" MacBook Pro (Model ID: MacBookPro13,3) running MacOS 12.6.8.  This didn't happen when I was test driving the Free version for the last week.

Things I've tried that haven't made a difference: 
* Rebooting
* Reinstalling the Helper
* Removing and installing the helper
* Resetting the Settings
* Removing the Helper and deleting then reinstalling AlDente 

All AlDente Settings are in the default state.

I'll also reach out to support via e-mail.

Below is a partial crash log. Let me know if you'd like the full crash log. 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               AlDente [1178]
Path:                  /Applications/AlDente.app/Contents/MacOS/AlDente
Identifier:            com.apphousekitchen.aldente-pro
Version:               1.22.2 (42)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-20 18:35:08.8507 -0400
OS Version:            macOS 12.6.8 (21G725)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        3E9A2F3C-6535-2C30-BAC0-FBD89350A0CF

Sleep/Wake UUID:       83887DDF-0784-465D-A06B-9132EBD5495C

Time Awake Since Boot: 3000 seconds
Time Since Wake:       1013 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       UNKNOWN_0xD at 0x0000000000000000
Exception Codes:       0x000000000000000d, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1178]

VM Region Info: 0 is not in any region.  Bytes before following region: 4396433408
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1060c4000-1063dc000    [ 3168K] r-x/r-x SM=COW  ...MacOS/AlDente

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	    0x7ff81e8990c9 swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags) + 73
1   libswiftCore.dylib            	    0x7ff81e899322 swift_beginAccess + 66
2   SwiftUI                       	    0x7ff91d2ad426 GraphHost.flushTransactions() + 362
3   SwiftUI                       	    0x7ff91d2ae304 closure #1 in closure #1 in closure #1 in GraphHost.asyncTransaction<A>(_:mutation:style:mayDeferUpdate:) + 15
4   SwiftUI                       	    0x7ff91c9026aa partial apply for closure #1 in ViewGraphDelegate.updateGraph<A>(body:) + 17
5   SwiftUI                       	    0x7ff91d113ca8 closure #1 in ViewRendererHost.updateViewGraph<A>(body:) + 69
6   SwiftUI                       	    0x7ff91d1128df ViewRendererHost.updateViewGraph<A>(body:) + 78
7   SwiftUI                       	    0x7ff91d120cd0 protocol witness for ViewGraphDelegate.updateViewGraph<A>(body:) in conformance NSHostingView<A1> + 25
8   SwiftUI                       	    0x7ff91c8fb2a4 ViewGraphDelegate.updateGraph<A>(body:) + 55
9   SwiftUI                       	    0x7ff91c9025e3 protocol witness for GraphDelegate.updateGraph<A>(body:) in conformance NSHostingView<A1> + 25
10  SwiftUI                       	    0x7ff91d2ae2e0 closure #1 in GraphHost.init(data:) + 122
11  SwiftUI                       	    0x7ff91d2af14e partial apply for closure #1 in closure #1 in GraphHost.asyncTransaction<A>(_:mutation:style:mayDeferUpdate:) + 19
12  SwiftUI                       	    0x7ff91c903e3c thunk for @escaping @callee_guaranteed () -> () + 12
13  SwiftUI                       	    0x7ff91d19325b partial apply for thunk for @escaping @callee_guaranteed () -> () + 17
14  SwiftUI                       	    0x7ff91d190b20 static NSRunLoop.flushObservers() + 118
15  SwiftUI                       	    0x7ff91d1931d8 closure #1 in closure #1 in static NSRunLoop.addObserver(_:) + 16
16  SwiftUI                       	    0x7ff91d18d716 specialized thunk for @callee_guaranteed () -> (@error @owned Error) + 14
17  libswiftObjectiveC.dylib      	    0x7ff826098e7c autoreleasepool<A>(invoking:) + 44
18  SwiftUI                       	    0x7ff91d1931c0 closure #1 in static NSRunLoop.addObserver(_:) + 35
19  SwiftUI                       	    0x7ff91d193205 @objc closure #1 in static NSRunLoop.addObserver(_:) + 43
20  CoreFoundation                	    0x7ff8111af500 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
21  CoreFoundation                	    0x7ff8111af392 __CFRunLoopDoObservers + 543
22  CoreFoundation                	    0x7ff8111ae947 __CFRunLoopRun + 1131
23  CoreFoundation                	    0x7ff8111ade1c CFRunLoopRunSpecific + 562
24  HIToolbox                     	    0x7ff819e5b5e6 RunCurrentEventLoopInMode + 292
25  HIToolbox                     	    0x7ff819e5b34a ReceiveNextEventCommon + 594
26  HIToolbox                     	    0x7ff819e5b0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
27  AppKit                        	    0x7ff813be8f6d _DPSNextEvent + 927
28  AppKit                        	    0x7ff813be762a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
29  AppKit                        	    0x7ff813bd9cd9 -[NSApplication run] + 586
30  AppKit                        	    0x7ff813badc57 NSApplicationMain + 817
31  AlDente                       	       0x1060d1f9c 0x1060c4000 + 57244
32  dyld                          	       0x115e0d52e start + 462

**Comment by MatthiasKerbl** [comment]
Hi @tcpulley,

thank you for reporting this bug. There is already a GitHub issue open here #1003.
We are working on a fix and will release it with one of the next updates.

Best,
Matthias
