### ISSUE TITLE
If I pay the pro version can I have support added for a hackintosh laptop?

### ISSUE THREAD

**Issue by RobyRew** [davidwernhart/AlDente-Charge-Limiter#284]
I have a hackintosh laptop ([Here my guide](https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_Updated_OpenCore_0.6.8)) and im using [VirtualSMC](https://github.com/acidanthera/VirtualSMC) to read and write from my system, I can se my battery percentage, but AIDente its not able to edit the SMC to my

And I would like to know what values should be modified for compatibility with my laptop

[Download IORegistryExplorer](https://github.com/khronokernel/IORegistryClone)

Files:
[SMCBatteryManager.kext.zip](https://github.com/davidwernhart/AlDente/files/6450274/SMCBatteryManager.kext.zip)
[Asus FX504.ioreg.zip](https://github.com/davidwernhart/AlDente/files/6450384/Asus.FX504.ioreg.zip)

**Comment by RobyRew** [comment]
thanks for nothing guys...

**Comment by DamonHD** [comment]
Why be rude?

You want help with a configuration explicitly unsupported by the creator of the OS, the project maintainer has signalled that they would need help, and I don't see that you've offered (say) money or time or any other effort to this end.

Rgds

Damon

**Comment by RobyRew** [comment]
> Why be rude?
> 
> You want help with a configuration explicitly unsupported by the creator of the OS, the project maintainer has signalled that they would need help, and I don't see that you've offered (say) money or time or any other effort to this end.
> 
> Rgds
> 
> Damon

I've just asked something, they/you could just respond "No" and close this "Issue", instead nobody even bother.
I sow that by buying Pro you would have support, my question was. If the support I asked can be provided with the Pro Subscription.
I can pay 20$ more on top of the Pro Subscription.

**Comment by MatthiasKerbl** [comment]
Hi @RobyRew,

Unfortunately, we do not see an easy way to add support for a Hackintosh laptop. Therefore, we can also not offer you to add support when you buy AlDente Pro. However, I would leave this issue open, if someone else knows more about this topic and wants to help. Otherwise, if you are not interested anymore, you can of course also close this issue.

Cheers,
Matthias
