### ISSUE TITLE
AlDente crash followed by several toggles not functioning after relaunching

### ISSUE THREAD

**Issue by fiveangle** [davidwernhart/AlDente-Charge-Limiter#667]
AlDente set to either regular or Intel mode with 70% target charge level stops showing "70%" and shows "0%" within an hour after starting. Left running many days (generally 1-5 days), it crashes with following log...

<details><summary>[Crashlog Summary (full crashlog attached)]</summary>

Process:               AlDente [22005]
Path:                  /Applications/AlDente.app/Contents/MacOS/AlDente
Identifier:            com.apphousekitchen.aldente-pro
Version:               1.16.1 (26)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           AlDente [22005]
User ID:               504

Date/Time:             2022-04-28 02:42:34.295 -0700
OS Version:            macOS 11.6.5 (20G527)
Report Version:        12
Anonymous UUID:        AFFE86A5-86EC-526B-638D-922D056ABE00

Sleep/Wake UUID:       475BBD4D-5BE4-4FF6-8469-E1A3C853E85A

Time Awake Since Boot: 220000 seconds
Time Since Wake:       120000 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: com.apple.libdispatch-manager

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [22005]

Application Specific Information:
Kernel bug: The kernel cannot allocate memory needed for the pseudo-receive.

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff204e1ba2 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff20461c1a nanosleep + 196
2   libsystem_c.dylib             	0x00007fff20461a82 sleep + 41
3   libxpc.dylib                  	0x00007fff2026f649 _waiting4memory + 14
4   libxpc.dylib                  	0x00007fff2025733f _xpc_mach_port_allocate + 92
5   libxpc.dylib                  	0x00007fff2025a59d xpc_connection_send_message_with_reply + 127
6   com.apple.Foundation          	0x00007fff213583ad -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 3114
7   com.apple.Foundation          	0x00007fff2135f198 -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:] + 135
8   com.apple.Foundation          	0x00007fff2135f10a _NSXPCDistantObjectSimpleMessageSend2 + 33
9   com.apphousekitchen.aldente-pro	0x000000010485a4af 0x10483b000 + 128175
10  com.apphousekitchen.aldente-pro	0x0000000104860b25 0x10483b000 + 154405
11  com.apphousekitchen.aldente-pro	0x0000000104884105 0x10483b000 + 299269
12  com.apphousekitchen.aldente-pro	0x0000000104882914 0x10483b000 + 293140
13  com.apple.Foundation          	0x00007fff213dce1f __NSFireTimer + 67
14  com.apple.CoreFoundation      	0x00007fff20624ca9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
15  com.apple.CoreFoundation      	0x00007fff2062479d __CFRunLoopDoTimer + 927
16  com.apple.CoreFoundation      	0x00007fff206242fa __CFRunLoopDoTimers + 307
17  com.apple.CoreFoundation      	0x00007fff2060aed3 __CFRunLoopRun + 1988
18  com.apple.CoreFoundation      	0x00007fff2060a04c CFRunLoopRunSpecific + 563
19  com.apple.HIToolbox           	0x00007fff28852a83 RunCurrentEventLoopInMode + 292
20  com.apple.HIToolbox           	0x00007fff288527e5 ReceiveNextEventCommon + 587
21  com.apple.HIToolbox           	0x00007fff28852583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
22  com.apple.AppKit              	0x00007fff22e12d72 _DPSNextEvent + 864
23  com.apple.AppKit              	0x00007fff22e11545 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
24  com.apple.AppKit              	0x00007fff22e03869 -[NSApplication run] + 586
25  com.apple.AppKit              	0x00007fff22dd7a6c NSApplicationMain + 816
26  com.apphousekitchen.aldente-pro	0x0000000104842c9c 0x10483b000 + 31900
27  libdyld.dylib                 	0x00007fff2052ff3d start + 1

Thread 1:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff204df2aa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff204df61c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2060c55f __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff2060ac3f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation      	0x00007fff2060a04c CFRunLoopRunSpecific + 563
5   com.apple.CFNetwork           	0x00007fff24ab3358 0x7fff24873000 + 2360152
6   com.apple.Foundation          	0x00007fff21394447 __NSThread__start__ + 1068
7   libsystem_pthread.dylib       	0x00007fff205148fc _pthread_start + 224
8   libsystem_pthread.dylib       	0x00007fff20510443 thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff204df2aa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff204df61c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2060c55f __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff2060ac3f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation      	0x00007fff2060a04c CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff22f98e3a _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff205148fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff20510443 thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff20510420 start_wqthread + 0

Thread 4 Crashed:: Dispatch queue: com.apple.libdispatch-manager
0   libxpc.dylib                  	0x00007fff20274e93 _xpc_connection_release_message.cold.2 + 23
1   libxpc.dylib                  	0x00007fff20259618 _xpc_connection_release_message + 110
2   libxpc.dylib                  	0x00007fff2025946b _xpc_connection_handle_event_inline + 71
3   libdispatch.dylib             	0x00007fff2037fa50 _dispatch_mach_handle_or_push_received_msg + 100
4   libdispatch.dylib             	0x00007fff2038425f _dispatch_mach_msg_send + 1143
5   libdispatch.dylib             	0x00007fff203839b9 _dispatch_mach_send_drain + 338
6   libdispatch.dylib             	0x00007fff203802f8 _dispatch_mach_notification_merge_evt + 36
7   libdispatch.dylib             	0x00007fff203889d7 _dispatch_mach_notify_merge + 275
8   libdispatch.dylib             	0x00007fff20388a50 _dispatch_mach_notify_send_possible + 18
9   libdispatch.dylib             	0x00007fff20396e40 _Xmach_notify_send_possible + 33
10  libdispatch.dylib             	0x00007fff20397049 libdispatch_internal_protocol_server + 80
11  libdispatch.dylib             	0x00007fff20388b44 _dispatch_mach_notification_merge_msg + 93
12  libdispatch.dylib             	0x00007fff20387435 _dispatch_event_loop_merge + 112
13  libdispatch.dylib             	0x00007fff2037a336 _dispatch_kevent_worker_thread + 904
14  libsystem_pthread.dylib       	0x00007fff205114a5 _pthread_wqthread + 386
15  libsystem_pthread.dylib       	0x00007fff2051042f start_wqthread + 15

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x0000000010002004  rbx: 0x0000600003e64820  rcx: 0x00007fff20278486  rdx: 0x0000600003e64820
  rdi: 0x0000000010002004  rsi: 0x00007fbc81ee8810  rbp: 0x0000700001647710  rsp: 0x00007000016476f8
   r8: 0x0000ee71ba7f1340   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000010002004  r13: 0x0000000000000001  r14: 0x000060000343e600  r15: 0x000060000343e600
  rip: 0x00007fff20274e93  rfl: 0x0000000000010246  cr2: 0x00007fff80812be0
  
Logical CPU:     6
Error Code:      0x00000000
Trap Number:     6

Thread 4 instruction stream:
  59 60 0f 0b 48 89 f8 48-8d 0d 3f 37 00 00 48 89  Y`..H..H..?7..H.
  0d 98 dd 59 60 48 89 05-c1 dd 59 60 0f 0b 55 48  ...Y`H....Y`..UH
  89 e5 53 50 48 63 df 48-89 df e8 50 0d 00 00 48  ..SPHc.H...P...H
  8d 0d e0 36 00 00 48 89-d8 48 89 0d 6d dd 59 60  ...6..H..H..m.Y`
  48 89 05 96 dd 59 60 0f-0b 89 f8 48 8d 0d 01 36  H....Y`....H...6
  00 00 48 89 0d 54 dd 59-60 48 89 05 7d dd 59 60  ..H..T.Y`H..}.Y`
 [0f]0b 89 f8 48 8d 0d 35-36 00 00 48 89 0d 3b dd  ....H..56..H..;.	<==
  59 60 48 89 05 64 dd 59-60 0f 0b 48 8d 0d 62 36  Y`H..d.Y`..H..b6
  00 00 48 89 0d 24 dd 59-60 0f 0b 55 48 89 e5 41  ..H..$.Y`..UH..A
  56 53 89 f3 49 89 fe 31-ff e8 e1 0c 00 00 41 8b  VS..I..1......A.
  06 48 c1 e3 20 48 09 d8-48 8d 0d ce 36 00 00 48  .H.. H..H...6..H
  89 0d f7 dc 59 60 48 89-05 20 dd 59 60 0f 0b 55  ....Y`H.. .Y`..U
  
Thread 4 last branch register state not available.

[Binary images available in attached complete log]

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=894.6M resident=0K(0%) swapped_out_or_unallocated=894.6M(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG image                          1124K       15 
CG raster data                     132K        4 
CoreAnimation                      576K       46 
CoreGraphics                        12K        2 
CoreUI image data                 5156K       36 
Foundation                          44K        2 
Image IO                             8K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.7G      182 
MALLOC guard page                   48K       12 
SQLite page cache                  128K        2 
STACK GUARD                       56.0M        5 
Stack                             10.0M        5 
VM_ALLOCATE                       1100K       10 
__DATA                            20.4M      457 
__DATA_CONST                      25.8M      300 
__DATA_DIRTY                      1529K      188 
__FONT_DATA                          4K        1 
__LINKEDIT                       501.2M       10 
__OBJC_RO                         70.3M        1 
__OBJC_RW                         2496K        2 
__TEXT                           393.5M      461 
__UNICODE                          588K        1 
libnetwork                         640K       16 
mapped file                      462.3M       33 
shared memory                      748K       14 
===========                     =======  ======= 
TOTAL                              3.2G     1813 

Model: MacBookPro11,3, BootROM 432.60.3.0.0, 4 processors, Quad-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 2.19f12
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGTX750MItem, NVIDIA GeForce GT 750M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.9)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

</details>

Upon relaunch of AlDente, it correctly shows 70% again for target charge state, but several UI settings are no longer able to be used:

![Screen Shot 2022-04-28 at 09 25 22](https://user-images.githubusercontent.com/2219447/165799890-56a9b466-171f-45c6-88ed-90a780ee84fb.jpg)

All UI elements on other pages are able to be used.

**Other details**
Calibration mode is never able to be finished once the battery state indicator spontaneously and incorrectly goes from "70%" to "0%", instead resulting in computer charging all the way to 100% and never entering discharge phase of calibration.

[AlDenteCrashlog.txt](https://github.com/davidwernhart/AlDente/files/8584649/AlDenteCrashlog.txt)

**Comment by MatthiasKerbl** [comment]
Hi @fiveangle,

Which MacBook model do you have?

When Intel Mode is activated, all features except for the Charge Limiter, are not available anymore.
You can read more about it here: https://apphousekitchen.com/feature-explanation-intel-mode/

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @fiveangle,

Do you still experience this issue with our newest version AlDente 1.19.1?

Cheers,
Matthias

**Comment by fiveangle** [comment]
Sorry for the delay. I have not used that MBP since filing. I will test with 1.19.1 and report back.

**Comment by MatthiasKerbl** [comment]
Hi @fiveangle,

Since you have not reported back in a while, I will close this issue for now. However, feel free to get back and I will open the issue again.

Cheers, Matthias
