### ISSUE TITLE
Power adapter broke down on MBP 16 2021 M1 Pro

### ISSUE THREAD

**Issue by etiennedupont** [davidwernhart/AlDente-Charge-Limiter#668]
**Describe the bug**

Hi, quick disclaimer that this might totally be a red herring. 

I started using AlDente since I got my MBP 3 months ago and I love it! Unfortunately, this week my power adapter suddenly stopped working. I'll have it changed by Apple but since I was told that this was a rare failure case I wanted to know if there can be a link with AlDente:
- [For the community] Did anybody with a similar setup experienced some similar problem?
- [For the maintainers] Could AlDente be somehow related to this issue?

**Comment by MatthiasKerbl** [comment]
Hi @etiennedupont,

So far, no one reported their power adapter breaking down after using AlDente, and I have no idea how AlDente could be related to this.

Cheers,
Matthias

**Comment by JorshyBitz** [comment]
I have had my MagSafe 3 cord go 2 times now and I use aldente on the daily. I am not sure if it is related but I am getting another cord under warranty. I may uninstall it when I get my new cord.

**Comment by etienne-dupont-skydio** [comment]
> I have had my MagSafe 3 cord go 2 times now and I use aldente on the daily. I am not sure if it is related but I am getting another cord under warranty. I may uninstall it when I get my new cord or after the third potential warranty replacement.

Thank you for reporting, did you change the power adapter too or only the cord?

**Comment by JorshyBitz** [comment]
I changed the power cord only under warranty. I tested it with other power adapters as well to make sure it was the cord though.

**Comment by JorshyBitz** [comment]
> > I have had my MagSafe 3 cord go 2 times now and I use aldente on the daily. I am not sure if it is related but I am getting another cord under warranty. I may uninstall it when I get my new cord or after the third potential warranty replacement.
> 
> 
> 
> Thank you for reporting, did you change the power adapter too or only the cord? 

I changed the cord only under warranty. However, I did use another power adapter to test and make sure the cord was the issue.

**Comment by Jerry23011** [comment]
Same spec, it's been over 8 months now and it works perfectly well with AlDente on, might be the quality issue of that specific charger.

**Comment by JorshyBitz** [comment]
> Same spec, it's been over 8 months now and it works perfectly well with AlDente on, might be the quality issue of that specific charger.

So far mine has been good for about 2 months. I guess two bad cables is necessarily possible. If it happens again I will update here.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Since it seems like these were just rare occasions of faulty chargers or cords, I will close this issue.
Hope that's understandable and feel free to share any new findings if something new comes up about this.

Cheers,
Matthias

**Comment by Oskar-cmyk** [comment]
I had the same question. I never had problem with power adapter. I had Mac for 1 and a half year, before Mac other Mac for 10 year no problem. I  started using aldente on my newly old Mac my adapter died in 4 months (since using aldente). Maybe not related but I am scared of using aldente cause of this.

**Comment by etiennedupont** [comment]
> I had the same question. I never had problem with power adapter. I had Mac for 1 and a half year, before Mac other Mac for 10 year no problem. I started using aldente on my newly old Mac my adapter died in 4 months (since using aldente). Maybe not related but I am scared of using aldente cause of this.
> 
> Maybe it is related to firmware updating on the power supply, and having aldente in bettwen. (when it broke I checked for updates, and I saw that the power adapter had just had updated before).

For what is worth @Oskar-cmyk I'm still using the same replacement power adapter since my original post and I did not get any new issue related to this. I do think this was just a coincidence, sorry for the noise.

**Comment by Oskar-cmyk** [comment]
> > I had the same question. I never had problem with power adapter. I had Mac for 1 and a half year, before Mac other Mac for 10 year no problem. I started using aldente on my newly old Mac my adapter died in 4 months (since using aldente). Maybe not related but I am scared of using aldente cause of this.
> > Maybe it is related to firmware updating on the power supply, and having aldente in bettwen. (when it broke I checked for updates, and I saw that the power adapter had just had updated before).
> 
> For what is worth [@Oskar-cmyk](https://github.com/Oskar-cmyk) I'm still using the same replacement power adapter since my original post and I did not get any new issue related to this. I do think this was just a coincidence, sorry for the noise.

Oh, thanks thats good to hear! I will reconsider it, is probably a coincidence.
