### ISSUE TITLE
Control MagSafe Charging LED Colors

### ISSUE THREAD

**Issue by adrian70000** [davidwernhart/AlDente-Charge-Limiter#68]
Hello,

Thanks for making this awesome tool. I use Macbook Air 2015 with a Magsafe charger. App works great and stops charging the battery but Magsafe light still remains orange instead of turning green. Is that normal?

**Comment by aomizu** [comment]
yes it's normal. it just means that the battery is not fully charged. but there is still power running through the charger, which is used up by the components instead of charging the battery

**Comment by Cyberdroid1** [comment]
I think making it green should be better, or, as an option.

**Comment by Cheule** [comment]
> I think making it green should be better, or, as an option.

I could be mistaken, but my assumption is that the green/amber light in the old MagSafe connectors is triggered by battery voltage, not the OS.  So, if your battery SOC is less than 8.4v (for a 2 cell config) it's likely to show as amber on the MagSafe.  FWIW, there's no good way to know how much mAh is left in a battery, it's always a guesstimate based on voltage readings.

**Comment by Cyberdroid1** [comment]
From https://github.com/godly-devotion/charge-limiter

![image](https://user-images.githubusercontent.com/51435948/104682537-e94f8100-571a-11eb-8ffa-e356e2da5601.png)

I hope this clarifies :D

**Comment by Cheule** [comment]
I stand corrected!  Thanks for posting.

**Comment by Cyberdroid1** [comment]
@davidwernhart Can you please implement this? Sorry for pinging 😅

**Comment by hpapagaj** [comment]
Following. This would be great. I also have orange light, but the app works great.

<img width="732" alt="Screenshot 2021-01-16 at 23 04 00" src="https://user-images.githubusercontent.com/72989831/104824096-582df680-584f-11eb-9317-2deab3513aca.png">

**Comment by Fenderman2** [comment]
Any update on this? It would be great if this could be added (max optional) in one of the next releases. It seems like the codebase is already there?
https://github.com/godly-devotion/charge-limiter

Thanks in advance!

**Comment by vvalzon** [comment]
This would make a huge difference! The ability to see if your charge is complete without opening the computer is incredibly convenient, and this issue is one of the only things that makes me waffle about using Al Dente!

**Comment by CollinQuiason** [comment]
Bump

**Comment by cmalex23** [comment]
So any reason why the code from the `charge-limiter` app wasn't merged?

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.20 with a new beta feature called "Control MagSafe LED" which will finally properly indicate if the Charge Limit is reached. You can read more about this feature on our blog here: https://apphousekitchen.com/feature-explanation-control-magsafe-led/

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Since we have finally implemented the features requested, I will close this issue.

Cheers,
Matthias
