### ISSUE TITLE
Update 1.17.1 lose settings for Charge limit

### ISSUE THREAD

**Issue by Volodymyr-13** [davidwernhart/AlDente-Charge-Limiter#687]
**Describe the bug**
Update 1.17.1 lose settings for Charge limit
It was on charging state at around 76% when I fired update process. After app relaunch I saw it's not charging, so I right clicked on menu bar and it started to charge, but I noticed also that it's now 100% limit, checked it with settings, gave me that screen-shoot. 

**To Reproduce**
1. Update to 1.17.1
2. Open Settings of the app
3. Notice now it's 100%
4. Set it to 80%, notice it's still showing 95% sail.

**Expected behavior**
Settings not lose after update.

**Screenshots**

Screenshoot taken after I realized that settings are lost, so I set from 100% to 80% limit.

<img width="468" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/169865603-84c29434-5ea9-412f-85e5-731bf57a8fb9.png">

**MacBook (please complete the following information):**
 - MacBook Pro M1 2021
 - macOS version 12.4
 - AlDente Pro 
 - AlDente 1.17.1

**Comment by jmvdkolk** [comment]
@KAMIKAZEUA. I have similar issues and need to open a support case. I think the problem is an incompatibility between AlDente and MacOS version 12.4. I did not have issues when still on MacOS version 12.3. Problems started with MacOS version 12.4.

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

It seems like you changed the Charge Limit to 100% after the update with the right-click on the menu bar icon.
Do you know about the Right-Click feature of AlDente Pro?
<img width="380" alt="Screenshot 2022-10-31 at 14 00 10" src="https://user-images.githubusercontent.com/33470003/199013749-a19bdf55-3752-45a1-af9a-711daf01a5d1.png">

Did you experience this issue with the latest updates?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

Did you experience this issue throughout the last couple of updates or do you think that it might be possible that you triggered the Right-Click feature unintentionally?

Cheers,
Matthias

**Comment by jmvdkolk** [comment]
Hi Matthias,

Thank you for following up. I am very happy to say that I have not experienced this issue throughout the last couple of updates. Thank you for the amazing support.

Cheers,
Jean-Marc
