### ISSUE TITLE
Temporarily disable “Stop charging when sleeping” until top-up finishes

### ISSUE THREAD

**Issue by DamonHD** [davidwernhart/AlDente-Charge-Limiter#707]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to ensure that my laptop is fully charged but don't want to have to artificially keep it awake to let it charge (I normally have the “Stop charging when sleeping” feature enabled).

**Describe the solution you'd like**
When the top-up action has been activated, temporarily disable “Stop charging when sleeping” until top-up finishes.

**Comment by MatthiasKerbl** [comment]
Hi @DamonHD,

We have just released AlDente Pro 1.20 which will automatically deactivate Stop Charging when Sleeping when TopUp gets is activated.

Cheers,
Matthias

**Comment by DamonHD** [comment]
Thank you!  I shall enable “Stop charging when sleeping” now!

Rgds

Damon
