### ISSUE TITLE
Reinstall helper application unavailable after canceling password dialog

### ISSUE THREAD

**Issue by retospect** [davidwernhart/AlDente-Charge-Limiter#751]
**Describe the bug**
Reinstall helper application unavailable after cancel.

**To Reproduce**
1. Click "Reinstall" button
2. Click OK in "Update Helper" popup
3. Click Cancel in the password dialog
4. Click "Reinstall" button again

**Expected behavior**
Process should repeat, ie, "Update Helper" popup should show again.
But nothing happens. Maybe forgot to dispose of Update Helper popup correctly?
Restarting app makes the button work again.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model M1 MBP
 - macOS version latest
 - AlDente Pro or AlDente Free? Pro
 - AlDente Version? 1.17.1
 - List of all enabled/disabled settings in AlDente:

**Comment by MatthiasKerbl** [comment]
Hi @retospect,

Thank you for telling us about this bug. We will try to fix it with one of the next updates.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @retospect,

This issue got fixed.

Best,
Matthias
