### ISSUE TITLE
Battery drain so fast after use this app for two week

### ISSUE THREAD

**Issue by Pisey-Nguon** [davidwernhart/AlDente-Charge-Limiter#795]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @Pisey-Nguon,

Please fill out the questions above and give a precise description of the potential bug you experience. Otherwise, I won't be able to assess this issue.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @Pisey-Nguon,

Since I haven't heard back from you, I will close this issue for now. However, feel free to fill out the questions above and I will open this issue again.

Cheers,
Matthias
