### ISSUE TITLE
(1.19.2) settings reset when you click on manage license

### ISSUE THREAD

**Issue by vladandrei51** [davidwernhart/AlDente-Charge-Limiter#821]
Settings reset (options toggles etc) when you click on General -> Manage License -> Cancel  (without actually doing anything to your subscription/license)

**Comment by MatthiasKerbl** [comment]
Hi @vladandrei51,

Thanks for pointing that out.
We will try to fix it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @vladandrei51,

We have fixed this issue with our newest version AlDente 1.20.

Cheers,
Matthias
