### ISSUE TITLE
A notice from AlDente-Pro shows up when mac restarts but it flashes past so quickly 

### ISSUE THREAD

**Issue by connor-circle** [davidwernhart/AlDente-Charge-Limiter#827]
**Describe the bug**
A notice from AlDente-Pro shows up "sometimes" when mac restarts but it flashes past so quickly. I have tried to record my screen by phone, but the notice pops up randomly, so I haven't seen it until now. 

**To Reproduce**
1. Restart Mac 
2. login my account and wait the system load items(including AlDente-Pro)
3. See the notice(sometimes)

**Expected behavior**
At least let me see what it is on the notice 
**MacBook (please complete the following information):**
 - Macbook air M1 2020
 - Ventura 13.0.1
 - AlDente Pro 
 - AlDente Version-1.19.2
 - List of all enabled/disabled settings in AlDente:
<img width="417" alt="P 2022-11-19 at 14 04 09" src="https://user-images.githubusercontent.com/35033310/202837077-4f9853a4-e33f-47ef-b27d-111a66bffa3a.png">
<img width="408" alt="P 2022-11-19 at 14 03 56" src="https://user-images.githubusercontent.com/35033310/202837109-2ec01e3f-616a-4956-a545-5cd91546b980.png">
<img width="423" alt="P 2022-11-19 at 14 04 03" src="https://user-images.githubusercontent.com/35033310/202837113-872c7d84-9219-43fc-b8e8-7ce3079e9838.png">

**Additional context**
I just want to know what the notice want to inform me of. I have checked the Q&A but nothing refer to it so I think the dear developer should know that.

**Comment by MatthiasKerbl** [comment]
Hi @connor-circle,

This might be the warning message that the AlDente helper app is not running. This can happen when your MacBook is just getting powered on and the main AlDente app started slightly before the helper app. Therefore, the main app thinks the helper app is missing but when the helper starts as well only shortly after, the message is gone again. This should not result in any other issues.

Cheers,
Matthias

**Comment by connor-circle** [comment]
> Hi @connor-circle,
> 
> This might be the warning message that the AlDente helper app is not running. This can happen when your MacBook is just getting powered on and the main AlDente app started slightly before the helper app. Therefore, the main app thinks the helper app is missing but when the helper starts as well only shortly after, the message is gone again. This should not result in any other issues.
> 
> Cheers, Matthias

Thanks your detailed reply! Have a nice day!
