### ISSUE TITLE
Black Friday Sale! -20% on AlDente Pro

### ISSUE THREAD

**Issue by MatthiasKerbl** [davidwernhart/AlDente-Charge-Limiter#832]
Hi everyone,

If you are interested in AlDente Pro, you can get it now at 20% cheaper for a limited time only.

What’s AlDente Pro?
AlDente Pro is our paid version of AlDente. It has many more features such as Heat Protection, Sailing Mode, Top Up, Calibration Mode,... It offers a better design and has live status icons. If you are interested in getting the most out of your battery, check out our website: https://apphousekitchen.com/pricing

Cheers,

David and Matthias

**Comment by adnanlionking** [comment]
I need discount kindly tell mE
