### ISSUE TITLE
not working properly on mbp 14 m1 pro

### ISSUE THREAD

**Issue by xxMosho** [davidwernhart/AlDente-Charge-Limiter#848]
whenever I set a limit it always exceed the limit 
also when I try to discharge it keeps going from to discharge to charging every couple of seconds

**Comment by MatthiasKerbl** [comment]
Hi @xxMosho,

Did you do a macOS update recently?

Cheers,
Matthias

**Comment by xxMosho** [comment]
yes but that was before using the app

**Comment by MatthiasKerbl** [comment]
> yes but that was before using the app

This still might have triggered a known bug #768.
Please try the following steps:

> To get AlDente to work again, please try the following steps which have worked for many users before:
> 
> 1. Unplug and discharge your MacBook to less than your current charge limit in AlDente
> 2. Turn off your MacBook and close the lid for a couple of minutes
> 3. Unplug the power brick from the outlet and wait a couple of minutes
> 4. Turn on your MacBook and plug it in again
> 5. Check if it stops charging at the charge limit set in AlDente

Cheers,
Matthias

**Comment by xxMosho** [comment]
it worked fine after I uninstalled and then reinstalled the application with the uninstallation guide your provided on your website
thanks for helping <3

**Comment by MatthiasKerbl** [comment]
> it worked fine after I uninstalled and then reinstalled the application with the uninstallation guide your provided on your website thanks for helping <3 keep it up

I am glad it works again. :)

Cheers,
Matthias
