### ISSUE TITLE
Topup grayed out.

### ISSUE THREAD

**Issue by PaerToernell** [davidwernhart/AlDente-Charge-Limiter#851]
I just installed AlDente on my Mac with MOnterey 12.5.1 

The "Top up" is gray and i cant click on it. 

![image](https://user-images.githubusercontent.com/53477121/207400301-2df89cc9-40a2-4e34-8a04-856fd48a8840.png)

**Comment by MatthiasKerbl** [comment]
Hi @PaerToernell,

TopUp is a feature only available in AlDente Pro. You can read more about AlDente Pro and all its features on our website here: https://apphousekitchen.com/

Cheers,
Matthias
