### ISSUE TITLE
sailing mode isnot work

### ISSUE THREAD

**Issue by lambs13** [davidwernhart/AlDente-Charge-Limiter#852]
I turned on the sailing mode, and the settings are as shown in the attached picture, but the battery is always at 80%, and it will not sail to 60%.
<img width="432" alt="1" src="https://user-images.githubusercontent.com/55617991/207514682-8877adf3-dd08-476f-85a0-276b2a9c0741.png">
<img width="426" alt="2" src="https://user-images.githubusercontent.com/55617991/207514684-5f27f4ff-7d78-4659-8c98-e599a3779fe6.png">

**Comment by lambs13** [comment]
I turned on the sailing mode, and the settings are as shown in the attached picture, but the battery is always at 80%, and it will not sail to 60%.
<img width="432" alt="1" src="https://user-images.githubusercontent.com/55617991/207514482-531742a1-2ab1-4aaa-a4af-7b93de83d77a.png">
<img width="426" alt="2" src="https://user-images.githubusercontent.com/55617991/207514486-c4c10d0a-e951-4eed-b821-926040ec7274.png">

**Comment by MatthiasKerbl** [comment]
Hi @lambs13,

The Sailing Mode is working as intended. It is not designed to discharge your battery and it can take weeks for it to fall back to the lower end. Please read more about what the Sailing Mode does in our blog post here: https://apphousekitchen.com/feature-explanation-sailing-mode/

Cheers,
Matthias
