### ISSUE TITLE
Add TopUp as a Shortcuts in AlDente

### ISSUE THREAD

**Issue by paulkim718** [davidwernhart/AlDente-Charge-Limiter#859]
can you add the ability to enable "top up" via shortcuts? I'd like to hide the aldente icon and just have it running in the background, then use a shortcut to activate top up when necessary

**Comment by MatthiasKerbl** [comment]
Hi @paulkim718,

Yes, that's definitely something we can add. We will include it in one of the upcoming updates.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @paulkim718,

Top Up is now included as a Shortcut in AlDente.

Best,
Matthias
