### ISSUE TITLE
After 1.20 update, no option to change show/hide startup popup window.

### ISSUE THREAD

**Issue by taylor325** [davidwernhart/AlDente-Charge-Limiter#867]
After 1.20 update, no option to change show/hide startup popup window.
M1 MacBook Pro, Ventura 13.1
AlDente Version: 1.20 (Free)
![Screenshot 2023-01-05 at 16 00 17](https://user-images.githubusercontent.com/52882397/210810971-be59db51-6170-493e-8f25-ed65bd803427.png)

**Comment by MatthiasKerbl** [comment]
Hi @taylor325,

Thanks for letting us know.
We will enable these settings again with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @taylor325,

We have just released AlDente 1.21.1 which allows you to disable the Popup Window on Startup even in the free version.

Cheers,
Matthias
