### ISSUE TITLE
Temporary allow "Charging When Sleeping", after click "Top Up"

### ISSUE THREAD

**Issue by rekby** [davidwernhart/AlDente-Charge-Limiter#870]
**Is your feature request related to a problem? Please describe.**
I click "Top Up", then close my macbook for a night. At morning I found macbook with same battery level as close it. Cause: enabled mode: "Stop Charging When Sleeping".

**Describe the solution you'd like**
Temporary turn off option "Stop Charging When Sleeping" when "Top Up" enabled: after click the button I want 100% charged battery and no need restrictions in sleep mode.

**Describe alternatives you've considered**
Stay macbook with open lid with disable sleep mode, disable the option manually.

**Comment by MatthiasKerbl** [comment]
Hi @rekby,

Do you have the newest version of AlDente (1.20) installed?
Because we fixed the exact issue you are facing with the newest version.

Cheers,
Matthias

**Comment by rekby** [comment]
@MatthiasKerbl try with 1.20 - problem solved, thanks :)
