### ISSUE TITLE
Issue with Paddle

### ISSUE THREAD

**Issue by GlycineMax** [davidwernhart/AlDente-Charge-Limiter#875]
Hello,

Maybe this is not the best option to solve this, but it was the only one I could think. I bought a lifetime pro version of Aldente a couple of days ago and have yet to receive a key or a confirmation e-mail.

I contacted Paddle about it, and they could not find a purchase in their system. I sent them the confirmation page after payment, a screenshot showing the card charge, my card information (a debit gift card was used), and e-mail, but they could not find my subscription.

Paddle ended up just saying, "Looking into this further, I can confirm that this purchase was not fulfilled by Paddle but by a different merchant. I would suggest that you get in touch with the merchant directly or with your bank to find out who charged you." So now I have a card charge that can not be refunded (gift card) and no subscription.

Btw, Paddle customer support is horrible and would not even read why I contacted them. They would e-mail me things like this "I understand that you want to **[Reason]**." I love the free version of the app so far, but this issue really gives me a reson not to recommend it to anybody.

I hope to get it fixed and get my subscription.
<img width="561" alt="image" src="https://user-images.githubusercontent.com/69690046/212136737-776685b5-6e2a-4d32-bd13-74cde66424ec.png">
[Purchase confirmation page.pdf](https://github.com/davidwernhart/AlDente-Charge-Limiter/files/10404238/Purchase.confirmation.page.pdf)

**Comment by MatthiasKerbl** [comment]
Hi @GlycineMax,

I am sorry for this horrible user experience.
Please send me an email with all the payment details to news@apphousekitchen.com from the email address you used during your purchase and I will either send you the license key or refund the money depending on what you want.

Cheers,
Matthias
