### ISSUE TITLE
Didn’t received emails for Al Dente Pro

### ISSUE THREAD

**Issue by shammtlb** [davidwernhart/AlDente-Charge-Limiter#880]
Hi, 

I haven’t received any email after i paid for the pro version. Not sure whether i typed my email wrong.

My email: shammtlb@gmail.com
Payment: 5904

**Comment by MatthiasKerbl** [comment]
Hi @shammtlb,

You had a typo in your email address. I have forwarded the purchasing emails to shammtlb@gmail.com now.

Cheers,
Matthias
