### ISSUE TITLE
USB-C charger doesn't charge no matter the percentage when aldente is on

### ISSUE THREAD

**Issue by jonny333** [davidwernhart/AlDente-Charge-Limiter#881]
**Describe the bug**
I installed aldente and set the limiter to 80%. However if I'm charging via a USB-C the battery shows "battery is not charging" no matter what, even if the percentage is below 80. If I plug-in the Magsafe it starts charging though. 
**To Reproduce**
1. install aldente free and set limiter to 80%
2. ensure your battery is below 80%
3. plugin USB-C charger (in my case 65W) 
4. The battery state stays at "battery is not charging"

**Expected behavior**
The battery to charge itself up to 80% and then stop, no matter what method of charging is used. 
**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model 14" M1 Pro Macbook pro 
 - macOS version 13.1
 - AlDente Pro or AlDente Free? Free
 - AlDente Version? 1.20
 - List of all enabled/disabled settings in AlDente: Limiter set to 80%, dock icon hidden

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @jonny333,

Usually, AlDente does not make any difference between MagSafe or USB-C charging.
Unfortunately, we are currently not able to recreate this issue on our MacBook.
Are you still experiencing this issue?
Did you try to completely reinstall AlDente?

**Comment by MatthiasKerbl** [comment]
Hi @jonny333,

Any updates on this issue?

**Comment by MatthiasKerbl** [comment]
Hi @jonny333,

Noting the extended period since our last communication, I am proceeding to close this issue for the time being. Please remember that should you need to revisit this matter, don't hesitate to reach out. I'll be more than happy to reopen the issue and assist you further.

Best,
Matthias
