### ISSUE TITLE
Prompted to install update, Macbook Pro now entering lock screen every five seconds.

### ISSUE THREAD

**Issue by tchpanda** [davidwernhart/AlDente-Charge-Limiter#885]
**Describe the bug**
I was prompted to install the latest update today (23 Jan).  Upon agreeing to do so my Macbook Pro enters lock screen after a only few seconds, repeatedly.

**To Reproduce**
1. Accept the latest update.
2. Observe maddening screen locking behaviour.

**Expected behavior**
Nothing.

**Screenshots**
N/A - I have removed this software.

**MacBook (please complete the following information):**
 - MacBook Pro 16-inch, 2021
 - macOS Ventura 13.1
 - AlDente Pro
 - AlDente Version - whatever has been released in the last day.
 - List of all enabled/disabled settings in AlDente:  N/A I have had to uninstall.

**Additional context**

**Comment by tchpanda** [comment]
Hi Matthias,

Sorry for the delayed response.  Reinstalled the helper and all appears fine now.

**Comment by MatthiasKerbl** [comment]
> Hi Matthias,
> 
> Sorry for the delayed response. Reinstalled the helper and all appears fine now.

Hi @tchpanda,

I am glad everything works as expected again.
I will close this issue for now but feel free to report back if anything is off again.

Cheers,
Matthias
