### ISSUE TITLE
Schedule charge start time

### ISSUE THREAD

**Issue by Sped0n** [davidwernhart/AlDente-Charge-Limiter#894]
**Is your feature request related to a problem? Please describe.**
Just want my laptop battery to be full and ready to go when I wake up.

**Describe the solution you'd like**
Ability to set the charge start time.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MatthiasKerbl** [comment]
> **Is your feature request related to a problem? Please describe.** Just want my laptop battery to be full and ready to go when I wake up.
> 
> **Describe the solution you'd like** Ability to set the charge start time.
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** N/A

Hi @Sped0n,

Thank you for your input. We already have a feature request like that open here #248, where I will also post updates about this topic. Therefore, I will close this issue.

Cheers,
Matthias
