### ISSUE TITLE
Calibration didn't stopped as should 

### ISSUE THREAD

**Issue by Volodymyr-13** [davidwernhart/AlDente-Charge-Limiter#895]
I started calibration and it didn't stopped at 81%, is counting it's discharge.

<img width="467" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/216846479-0d5afb5d-2e23-4db2-82ae-ae2deb036ae1.png">

<img width="432" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/216846486-0da9b710-9b26-490c-925c-325fd105a77e.png">

I stopped it on that moment, maybe it will check % from the system aka not real hardware battery percentage?

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

Thanks for the bug report. You are correct, in AlDente 1.20 we are using the macOS battery percentage for the Calibration Mode even if the Hardware Battery percentage is activated. However, we already fixed it and will release it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

We have just released a new version of AlDente Pro which includes a fix for this issue.

Cheers,
Matthias
