### ISSUE TITLE
"Show on Startup" Permanently Enabled for Free User on version 1.20

### ISSUE THREAD

**Issue by duemanisinistre** [davidwernhart/AlDente-Charge-Limiter#902]
**Describe the bug**
The "Show on Startup" is enabled by default for free users on a fresh installation of version 1.20 and cannot be disabled like in previous versions.

**To Reproduce**
1. Clean install of AlDente version 1.20 (no previous installations)
2. Settings > Appearance > Show on Startup - Enabled (cannot change)

**Expected behavior**
Ability to enable or disable Show on Startup for free users like in previous versions

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @duemanisinistre,

This will be fixed with the next update.
We already have an issue open for this here: #867
I will close this issue and provide any news on this in #867.

Cheers,
Matthias
