### ISSUE TITLE
Can calibratre mode auto run weekly or monthly？

### ISSUE THREAD

**Issue by sampr373** [davidwernhart/AlDente-Charge-Limiter#903]
**Describe the solution you'd like**
 
AlDente send a notice for the users to confirm the calibratre weekly.

**Comment by MatthiasKerbl** [comment]
Hi @sampr373,

Currently, the Calibration Mode needs to be triggered manually. However, we are working on a scheduling feature to which will allow to let the Calibration Mode run automatically.
Furthermore, we already have a feature request for this open here #676. Therefore, I will close this issue.

Cheers,
Matthias
