### ISSUE TITLE
Charge limit failure

### ISSUE THREAD

**Issue by hhrensheng** [davidwernhart/AlDente-Charge-Limiter#906]
Hello I am a foreigner。my english is not well。

![未命名](https://user-images.githubusercontent.com/29398035/224199880-2439a235-38bb-4b42-a920-d6e535871336.gif)

macOS:13.2.1
AlDente pro 1.20

**The following method doesn't work for me**
![image](https://user-images.githubusercontent.com/29398035/224200298-6ef2a177-4944-4899-9258-54298e368160.png)

**Comment by MatthiasKerbl** [comment]
Hi @hhrensheng,

Do you have Apple's Optimized Battery Charging disabled?
Did you try to reinstall the helper application in AlDente Settings/General/Reinstall?
Did you try to reinstall AlDente Completely? https://apphousekitchen.com/how-to-uninstall-aldente-pro/

Hope that helps.

Cheers,
Matthias

**Comment by hhrensheng** [comment]
Thank you.
After I updated the software to the latest version, it worked fine.
But I found another phenomenon：
During battery calibration，A prompt will be triggered: the power is disconnected, whether to continue battery calibration？
I don't think this prompt should appear。

**Comment by MatthiasKerbl** [comment]
> Thank you. After I updated the software to the latest version, it worked fine. But I found another phenomenon： During battery calibration，A prompt will be triggered: the power is disconnected, whether to continue battery calibration？ I don't think this prompt should appear。

Hi @hhrensheng,

I am glad it works now. :)
You are right, we should adapt the notification for this scenario.

Cheers,
Matthias
