### ISSUE TITLE
MagSafe3 LED control fails after upgrading from 1.20->1.21

### ISSUE THREAD

**Issue by dbavatar** [davidwernhart/AlDente-Charge-Limiter#908]
**Describe the bug**
After upgrading to 1.21 MagSafe only blinks green at approximately 2 second intervals.

**To Reproduce**
1. Upgrade from 1.20 to 1.21
2. Leave "Control Magsafe" enabled alone.

**Expected behavior**
Solid amber during charging, solid green when not charging

**MacBook (please complete the following information):**
2021 Macbook Pro M1 Max MacBookPro18,2
Ventura 13.2.1
AlDente Pro
1.21

**Comment by PPFilip** [comment]
Same here - M1 Max running on  13.2.1 (22D68) , AlDente Pro 1.21

**Comment by lakoliu** [comment]
Same here, just updated and this started happening right away. It worked as expected in 1.20.

**Comment by furrcodes** [comment]
Same here - 14" M1 Pro, MacOS 13.2.1 (22D68), AlDente Pro 1.21

**Comment by egehandr** [comment]
Same here - 14" M1 Pro, MacOS 13.2.1 (22D68), AlDente Pro 1.21

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thanks for sharing this bug and sorry for the inconvenience. We will try to release a fix as soon as possible. Until then it might be best to keep "Control MagSafe LED" disabled.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.21.1 which has a fix for the mentioned bug.

Cheers,
Matthias

**Comment by PPFilip** [comment]
Thank you! I can confirm that it is fixed on my side.

**Comment by MatthiasKerbl** [comment]
> Thank you! I can confirm that it is fixed on my side.

Perfect.
