### ISSUE TITLE
"Hardware Battery Percentage" not working under 1.21.1

### ISSUE THREAD

**Issue by ziggy029** [davidwernhart/AlDente-Charge-Limiter#914]
**Describe the bug**
Upon updating AlDente to 1.21.1, the battery indicator in the program jumped from 78% to 83%.  That 83% is the same as Apple's own utility displays; other utilities like Coconut Battery show 78%.

**To Reproduce**
Go into the setting and select "Charge".  Toggling 'Hardware Battery Percentage" on and off has no effect on the displayed battery percentage.  Also rebooted the system to see if that made a difference; it did not.  

**Expected behavior**
Expected the displayed battery percentage to drop to about 78% when this feature is toggled on.  

**Screenshots**
Screenshots attached -- note the same reported value (83%) whether this setting is on or off.
**MacBook (please complete the following information):**
MacBook Air M1 (2020, 16 GB/1 TB)  - macOS Ventura 13.2.1
 - AlDente Pro 1.21.1

**Additional context**
![Screenshot 2023-03-13 at 7 44 45 AM](https://user-images.githubusercontent.com/127764638/224736347-9133a72e-322b-4a8b-b53a-53791275fd15.png)
![Screenshot 2023-03-13 at 7 44 57 AM](https://user-images.githubusercontent.com/127764638/224736366-666b3ab3-2f59-4422-8792-760ab18a11e9.png)

![Screenshot 2023-03-13 at 7 55 55 AM](https://user-images.githubusercontent.com/127764638/224739665-af3ddb10-fce9-49b0-8454-1e335eeb7b78.png)

**Comment by MatthiasKerbl** [comment]
Hi @ziggy029,

Thanks a lot for the detailed bug report.
We have already released an update of AlDente (1.21.2) which includes a fix for this issue.

Cheers,
Matthias
