### ISSUE TITLE
Top Up charge greyed out

### ISSUE THREAD

**Issue by gijap** [davidwernhart/AlDente-Charge-Limiter#919]
The Discharge button works. Top up button next to it is greyed out.

Why is this? 

**To Reproduce**
1. click on Aldente icon

**Expected behavior**
Top Up feature

**Screenshots**
<img width="386" alt="image" src="https://user-images.githubusercontent.com/128024497/225538225-4a58855b-277d-4556-952d-ffa7e670bdba.png">

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608) Macbook pro 14-inch, 2021,   Model Identifier:	MacBookPro18,3
  Model Number:	G15J0B/A
 - macOS version (https://support.apple.com/en-us/HT201260) 13.1 
 - AlDente Pro or AlDente Free? Free
 - AlDente Version? 1.213

**Comment by MatthiasKerbl** [comment]
Hi @gijap,

The Top Up feature is only available in AlDente Pro. You can read more about the differences between AlDente Free and Pro here: https://apphousekitchen.com/

Cheers,
Matthias

**Comment by ADTC** [comment]
@MatthiasKerbl I suggest showing it somehow, like a pop-over or tooltip that says "Get Pro to enable this feature"

Same can be done for disabled toggles in the settings.
