### ISSUE TITLE
AlDente Sailing Mode

### ISSUE THREAD

**Issue by TheGlorySaint** [davidwernhart/AlDente-Charge-Limiter#923]
**Describe the bug**
After I have purchased AlDente Pro, the Sailing Mode works no more. I have set the ChargeLimit to 80 Percent. The Sailing Mode is active and set to 20 Percent, so it should sail between 80 and 60 Percent, but it doesn't. I haven't changed any setting else.

I reinstalled, closed the app, force closed it over Activity Monitor and reinstalled the Helper, but nothing fixed the issue.

**To Reproduce**
Can't really tell.
I bought AlDente Pro and now sailing isn't working anymore. 

**Expected behavior**
Sailing should work

**Screenshots**

![Bildschirm­foto 2023-03-27 um 16 41 25](https://user-images.githubusercontent.com/21318321/227974383-a8cc0e57-d2ae-4118-be55-5f03ad22fa94.png)
![Bildschirm­foto 2023-03-27 um 16 41 30](https://user-images.githubusercontent.com/21318321/227974395-b91f1a47-c85a-4c42-b4eb-26d7fd055d64.png)
![Bildschirm­foto 2023-03-27 um 16 41 34](https://user-images.githubusercontent.com/21318321/227974402-6f25053f-1433-4138-85b7-7339ed4462cb.png)
![Bildschirm­foto 2023-03-27 um 16 41 39](https://user-images.githubusercontent.com/21318321/227974405-682d351e-8253-4b75-ad0e-f10f7c009807.png)
![Bildschirm­foto 2023-03-27 um 16 41 45](https://user-images.githubusercontent.com/21318321/227974408-d740c4e3-5
![Bildschirm­foto 2023-03-27 um 16 41 08](https://user-images.githubusercontent.com/21318321/227974588-be0f75c5-e4da-48fa-8d7e-7ade8e68e9fe.png)
48c-40fb-8f26-5512eba95497.png)

**MacBook (please complete the following information):**
 - MacBook Pro 2021 16" M1 Pro 
 - macOS version Venture 13.2.1
 - AlDente Pro 
 - AlDente Version 1.21.3
 - List of all enabled/disabled settings in AlDente: See Screenshots

**Comment by TheGlorySaint** [comment]
@MatthiasKerbl

Yesterday, I had plugged in my MacBook to a Thunderbolt dock to use multiple displays, from where the MacBook gets also the Power. It stayed the whole day at 80%, and it never dropped below. MacBook is in Clamshell mode.

**Comment by MatthiasKerbl** [comment]
Hi @TheGlorySaint,

It really depends on these parameters (setting, MacBook model, charging setup, and usage behavior) when and how fast the battery level will drop. Especially, with the Apple Silicon MacBooks it can take a really long time before the battery level goes down. 

Cheers,
Matthias

**Comment by TheGlorySaint** [comment]
@MatthiasKerbl

Thank you for your response.

I'm an App Developer. I sit around 10–12 Hours per Day in front of my MacBook. With that in mind, never seen a drop of percentage in Battery, doesn't seem right for me. But i'm fine with that. Keep Up the good work.
