### ISSUE TITLE
Aldente need password for helper every boot

### ISSUE THREAD

**Issue by rekby** [davidwernhart/AlDente-Charge-Limiter#924]
**Describe the bug**
When I reboot my macbook I need every time enter my password to aldente helper installer.

**Expected behavior**
No need password without aldente update.

**MacBook (please complete the following information):**
 - MacBook model (MacBook Pro, 16-inch, 2021)
 - macOS version (13.2.1 (22D68))
 - AlDente Pro
 - AlDente Version: 1.21.3
 - List of all enabled/disabled settings in AlDente:

**Additional context**
I have two partitions on my mac with two separated macos, aldente install in every of the partitions.

**Comment by chepiok** [comment]
Same issue for me. Same hardware and software configuration.

**Comment by papas68** [comment]
Same issue for me. Same hardware and software configuration.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thank you for reporting this. We are aware of this bug and working hard on fixing it.
Also, we already have a Github issue open for this bug here #866 where I will post updates about this bug. Therefore, I will close this issue.

Cheers,
Matthias
