### ISSUE TITLE
Purchased a permanent version, but cannot activate it

### ISSUE THREAD

**Issue by wangyanglinux** [davidwernhart/AlDente-Charge-Limiter#928]
I have purchased AiDente, but it cannot be activated. My email is wangyanglinux@163.com

**Comment by MatthiasKerbl** [comment]
> I have purchased AiDente, but it cannot be activated. My email is [wangyanglinux@163.com](mailto:wangyanglinux@163.com)

Hi @wangyanglinux,

Thank you for your support in buying AlDente Pro and I am sorry you are having issues activating it.
Everything looks as expected in the backend and you should be able to activate AlDente Pro with the license code provided in the purchasing emails.
What exactly is the issue when you try to activate AlDente Pro?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @wangyanglinux,

Any updates about your issue?

Cheers,
Matthias
