### ISSUE TITLE
The power value displayed by Aldente is inconsistent with the system power.

### ISSUE THREAD

**Issue by jinweiisgreat** [davidwernhart/AlDente-Charge-Limiter#929]
**Describe the bug**
The power value displayed by Aldente is inconsistent with the system power.

**Expected behavior**
The value of AlDente is same as the system battery value.

**Screenshots**
<img width="160" alt="image" src="https://user-images.githubusercontent.com/69202833/230550978-14911d28-7c6b-4ef0-852a-7cbc2ff5a42f.png">

**MacBook (please complete the following information):**
 - MacBook pro 14 - M2 pro
 - macOS 13.3
 - AlDente Pro
 - AlDente Version? - AlDente 1.21.3

**Comment by MatthiasKerbl** [comment]
Hi @jinweiisgreat,

You have most likely turned on the AlDente Pro feature "Hardware Battery Percentage". This feature uses the more accurate battery percentage directly from the battery management system. You can read more about this feature **[here](https://apphousekitchen.com/feature-explanation-hardware-battery-percentage/)**.
If you want AlDente to use and show the same battery percentage as macOS, you need to open AlDente/Settings/Charge/Other and disable "Hardware Battery Percentage".

Cheers,
Matthias
