### ISSUE TITLE
Aldente pro email not received

### ISSUE THREAD

**Issue by always4113** [davidwernhart/AlDente-Charge-Limiter#932]
I purchased the aldente pro version and succeeded in paying, but I haven't received an email yet. I also checked the junk mail box. 

My email address : always4110@icloud.com 

Please check. 🙏

**Comment by MatthiasKerbl** [comment]
Hi @always4113,

You used the wrong email address (always4110@gmail.com instead of always4110@icloud.com). I have forwarded the purchasing emails to the correct email address now.

Cheers,
Matthias

**Comment by always4113** [comment]
Thanks!
