### ISSUE TITLE
Temporarily Disable Sailing/Discharge To Limit/Temporarily Ignore Temp Limit

### ISSUE THREAD

**Issue by pholvs** [davidwernhart/AlDente-Charge-Limiter#937]
I have three use-cases that I feel could be better supported right now:

1. AlDente currently supports the "top-up" feature, where the charge limit is temporarily ignored.  There are times when I'd basically like to top up but not necessarily to 100% - I want to start a charge cycle right now, but to stop at the normal charge limit.  Essentially this would be temporarily disabling sailing mode, and turning it on again in, say, an hour.
2. Other times, my laptop ends up charged to 100% and I would like it to discharge to the charge limit, but not to just continue discharging forever.
3. Finally, there are some situations when the laptop is warm but I need to charge the battery anyway, but I would like to resume temperature monitoring after the charge is completed.

Use-cases 1 and 3 can be generalized to 'ignore limits temporarily' - like if the enable/disable selectors had four positions: disable, enable after 30 minutes, disable after 30 minutes, and enabled.  Or next cycle, instead of a time period.  Or perhaps the time-limit could be a radio option/selector box underneath those options.

This can be managed manually of course, but, it would be nice to have an official option because I never remember to turn it on every time after my situation where I needed a quick charge is over!

**Comment by MatthiasKerbl** [comment]
Hi @pholvs,

Thank you for your comments and let me share my thoughts about your suggestions.

> 1. AlDente currently supports the "top-up" feature, where the charge limit is temporarily ignored. There are times when I'd basically like to top up but not necessarily to 100% - I want to start a charge cycle right now, but to stop at the normal charge limit. Essentially this would be temporarily disabling sailing mode, and turning it on again in, say, an hour.

It is already possible to do that by just changing the charge limit slightly. This will result in your MacBook charging to the new charge limit and afterward, it will start sailing again.

> 2. Other times, my laptop ends up charged to 100% and I would like it to discharge to the charge limit, but not to just continue discharging forever.

During Discharge, your MacBook will never continue discharging forever, it will always discharge to the set charge limit.

> 3. Finally, there are some situations when the laptop is warm but I need to charge the battery anyway, but I would like to resume temperature monitoring after the charge is completed.

The solution to this edge case is Top Up. During Top Up, Heat Protection is ignored and your MacBook will continue charging regardless of the temperature when Top Up is finished will return to recognizing Heat Protection again.

I hope you understand that we are trying to find a good middle ground between adding as much customizability as possible by still maintaining a certain degree of ease of use and convenience. This is also why we added Apple Shortcuts support a while ago that power user can start configuring AlDente Pro the way they really want it.

Cheers,
Matthias
