### ISSUE TITLE
Discharge button lack on Al Dente Pro

### ISSUE THREAD

**Issue by JardiinWD** [davidwernhart/AlDente-Charge-Limiter#943]
Helloo @MatthiasKerbl !

**Describe the bug**

I notice the lack of discharge mode/button on my macbook with Al Dente Pro. 

**MacBook/Al Dente version**

 - MacBook model : Pro 13" M1 - 8gb of RAM
 - macOS version : **Ventura 13.3.1**
 - AlDente Pro : **Pro**
 - AlDente Version: **1.21.4**.

**Screenshots**

![Screenshot 2023-04-24 alle 10 04 33](https://user-images.githubusercontent.com/93372660/233937425-910e1dba-66be-4df0-8e25-b620c1c8bfe0.png)

**Additional context**

In brief : Yesterday I tried the free version of Al Dente free (and had discharge mode available). I liked it and decided to buy the licence of Al Dente Pro. After that **I uninstalled the free version + the assistant**, downloaded Al Dente Pro.dmg and reinstalled by associating my licence key.

I look forward to your feedback,
Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @JardiinWD,

Thank you for your support in buying AlDente Pro.
The reason you are missing the discharge button is that you have the "Automatic Discharge" feature enabled. With this feature enabled, discharge starts automatically when you set the charge limit below the current battery level. This is also indicated by the orange slide bar and the minus which means discharging. If you prefer to manually trigger the "Discharge" feature, you can disable "Automatic Discharge" in Settings/Charge/Automatic Discharge. Afterward, the discharge button will appear again.
You can also read more about the [Discharge feature](https://apphousekitchen.com/feature-explanation-discharge/) and the [Automatic Discharge feature](https://apphousekitchen.com/feature-explanation-automatic-discharge/) on our blog.

Cheers,
Matthias
