### ISSUE TITLE
No licence mail.

### ISSUE THREAD

**Issue by Zeabraz** [davidwernhart/AlDente-Charge-Limiter#949]
Hey, bought the pro version just an hour ago. Transaction went through, and junk mail is empty. Maybe I typed wrong email or something. Please send a new mail. Cheers!
sebastian-brandt@hotmail.com

**Comment by MatthiasKerbl** [comment]
Hi @Zeabraz,

Thanks for your support.
I have just forwarded your purchasing emails again and your address seems to be correct. If you are still not receiving the emails, please contact the support of our merchant of record here: [assist@paddle.com](mailto:assist@paddle.com)

Cheers,
Matthias
