### ISSUE TITLE
I paid for pro version lifetime 

### ISSUE THREAD

**Issue by pywsa** [davidwernhart/AlDente-Charge-Limiter#953]
Hi I paid for pro version lifetime.
I made a typo in my email address and I never received the license. I tried contacting PADDLE but they were not helpful.
I mistakenly enter this email address "selv1970aa@pywsa.me" instead of the correct email which is : selv1970aa@pm.me

could you please check and send the license to this email?
Credit card used: xxxxx7994
Name: neville thomas

**Comment by MatthiasKerbl** [comment]
Hi @pywsa,

I have just forwarded the purchasing emails.

Cheers,
Matthias
