### ISSUE TITLE
Sailing Mode does not work as expected

### ISSUE THREAD

**Issue by sergiupopescu199** [davidwernhart/AlDente-Charge-Limiter#960]
**Describe the bug**
Sailing mode does not work as expected: I was expecting for Sailing mode to work after it charge the battery to 55% it should go to 45% & recharge again to 55% & so on but it stays on 55% all the time

<img width="411" alt="Screenshot 2023-06-02 at 11 44 10" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/44298302/c46b1491-d317-4a96-b4e6-9950b4901bd6">

My Config
![Screenshot 2023-06-02 at 11 49 58](https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/44298302/2b0e92e4-df47-4b60-a208-0a9ad07de544)

![Screenshot 2023-06-02 at 11 49 51](https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/44298302/c3010ede-1236-4b15-b88f-45cb80e735bf)
=

**MacBook (please complete the following information):**
 - MacBook model 13 inch M2 16GB
 - macOS version Ventura 13.4
 - AlDente Pro
 - AlDente Version -> 1.21.4
 - List of all enabled/disabled settings in AlDente:

**Comment by MatthiasKerbl** [comment]
Hi @sergiupopescu199,

This is actually the intended behavior of the Sailing Mode and looking at your screenshots, Sailing Mode is working as intended.
It is a common misconception that the Sailing Mode does actively charge and discharge your MacBook between the sailing range. This would actually be much worse for the battery.
You can read a detailed description of what the Sailing Mode actually does on our blog "[Feature Explanation: Sailing Mode](https://apphousekitchen.com/feature-explanation-sailing-mode/)"

Best,
Matthias

**Comment by sergiupopescu199** [comment]
@MatthiasKerbl Thank you for detailed explanation now I understood!
