### ISSUE TITLE
Power Flow MB 2017 Four TB not working

### ISSUE THREAD

**Issue by Oll0w4in** [davidwernhart/AlDente-Charge-Limiter#973]
**Describe the bug**
Since the Power Flow feature is in beta, I would like to report a bug on my MB Pro 2017 with four TB Ports. The new Power Flow feature is not showing anything at all. I will append an image of the stats site.

Let me know how I can help you with this bug.

**To Reproduce**

1. Install newest Version of AlDente
2. Activate Power Flow feature
3. Try to display the new feature in the app or in the menu bar

**Expected behavior**

**Screenshots**
<img width="420" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/29129081/43fbce65-e3e8-4715-abe5-8b52b34f023d">
<img width="397" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/29129081/145dcba4-d10f-4c4b-893e-84111e098825">

**MacBook (please complete the following information):**
 - MacBook model: MacBookPro14,2
 - macOS version 13.4 (22F66)
 - AlDente Pro
 - AlDente Version 1.22
 - List of all enabled/disabled settings in AlDente:
 - Start at login enabled
 - stop charging when sleep and turned off enabled
 - auto discharge enabled
 - hardware battery percent enabled
 - sailing enabled, 10% from 65%
 - heat protection enabled at 38°C
 - Show Popover enabled

**Comment by Rennleiter02** [comment]
Exactly the same problem (on identical model, macOS 13.4.1 (22F82))

**Comment by MatthiasKerbl** [comment]
Hi @Oll0w4in,

Thanks for letting us know, we will release a fixed version of AlDente which supports your model soon.
Further updates about this will be provided here #985.

Best,
Matthias
