### ISSUE TITLE
Menubar item cut off

### ISSUE THREAD

**Issue by stonerl** [davidwernhart/AlDente-Charge-Limiter#974]
**Describe the bug**
When setting the Menubar Icon to “Show percentage”, the percentage (%) symbol is cut off when the battery is charged to 100%. See the attached screenshot.

**Screenshots**
<img width="65" alt="CleanShot 2023-06-17 at 14 52 33@2x" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/2091312/61a07a56-a1ac-470a-ae9c-4891e3c3d0bf">

**MacBook (please complete the following information):**
 - MacBook Pro 14"
 - macOS 13.4
 - AlDente Pro
 - AlDente Version 1.22

**Comment by MatthiasKerbl** [comment]
Hi @stonerl,

Thanks for making us aware of this bug, we will fix it with the next update.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @stonerl,

This bug got fixed with our latest update.

Best,
Matthias
