### ISSUE TITLE
Power on does not start

### ISSUE THREAD

**Issue by Nshandeshu** [davidwernhart/AlDente-Charge-Limiter#991]
AIdente pro set boot up and will not achieve 
In mos system settings general login item add program does not respond 
AIdente pro；1.22
macbookpro 13.4.1
[![photo-2023-07-07-10-16-52.jpg](https://i.postimg.cc/xdjg6vpZ/photo-2023-07-07-10-16-52.jpg)](https://postimg.cc/sM8pXhrP)

**Comment by MatthiasKerbl** [comment]
Hi @Nshandeshu,

We are aware of this issue and will report updates about it here #898.

Best,
Matthias

**Comment by Nshandeshu** [comment]
> Hi @Nshandeshu,
> 
> We are aware of this issue and will report updates about it here #898.
> 
> Best, Matthias
hi
Is this problem still unresolved?
