### ISSUE TITLE
Sailing Mode for Heat Protection

### ISSUE THREAD

**Issue by Elijas** [davidwernhart/AlDente-Charge-Limiter#993]
**Is your feature request related to a problem? Please describe.**
- Sailing mode is supposed to prevent repeated charging / stopping charging.
- Heat Protection does exactly that 33 degrees (stop) -> 32.9 degrees (start) -> 33 degress (stop)

**Describe the solution you'd like**
Degrees sailing mode (e.g. selectable 1-5 degrees) 33 degrees (stop) -> 31 degrees (start) -> 33 degrees (stop)

**Describe alternatives you've considered**
Using lower powered charging brick to limit power and therefore heat

**Additional context**
n/a

**Comment by mojoba** [comment]
I second this feature request. 

I currently see rapid charge/discharge bouncing while connected to a 140w power supply and battery at or over 50% due to heat protection at 33c and battery at 32.9c.

Either a wattage limit while charging or a sailing mode for Heat Protection is ideal.

**Comment by MatthiasKerbl** [comment]
Hi @Elijas and @mojoba,

You are correct, an improvement of the Heat Protection feature in this direction would make a lot of sense and we will look into it.
I will close this issue since we already have a feature request open for this issue here #675.

Best,
Matthias
