### ISSUE TITLE
limit charge power of battery

### ISSUE THREAD

**Issue by TremotinoVolante** [davidwernhart/AlDente-Charge-Limiter#994]
Hi, 

I don't not if this is possible **via software**. But in 99% of the time I would have this feature activated:

**Describe the solution you'd like**
A button to activate charging power limit and a slider to set the charging power limit e.g. 5W to 100W

**Describe alternatives you've considered**
just use a charger with less power than the original macbook charger e.g. 45W instead of 135W charger. Using 45W charger has other disadvantages like overheating of the charger, and other...

**Additional context**
Battery live span (and battery temperature) is heavy influenced by the charging power. The faster batteries get charged the faster they get worn out. So since fast charing is nice and sometines needed it would be really cool to have the choice to limit the charging power, as for me most of the time charging time is not an issue. 

EDIT: this could be a possible solution to #993 to keep the temperature under a certain temperature threshold.

**Comment by MatthiasKerbl** [comment]
Hi @TremotinoVolante,

Such a feature would indeed make a lot of sense. Unfortunately, we were not able to find a possibility to implement it.
Also, we already have a feature request open for this #130.

Best,
Matthias
